# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Uncomment the line below if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds the app for iOS"
  
  lane :build_app_lane do
    build_app(scheme: "habitTracker")
  end
end

